### ISSUE TITLE
Code formatting doesn't work for yaml

### ISSUE THREAD

**Issue by TimoGlastra** [docuowl/docuowl#26]
When using codeblocks for yaml somehow all lines get squished into one, making it unusable. It works if you don't specify a language but that removes the nice syntax highlighting. I haven't encountered this with other languages.

Example:

![image](https://user-images.githubusercontent.com/23165168/144019720-d51ed3e5-3041-4a10-8816-10b097751765.png)

Sidenotes content:

	  #! Usage

	  ```yml
	  actions:
	    - id: something
	      uses: something/something@v1
	      something: else
	```
	  

This is not just the case with sidenotes, also if you place it in the `content.md` file.

Any idea why this is just happening with yaml?
